language: php
php:
  - 7.1.9

branches:
  only:
    master

before_install:
  - travis_retry composer self-update
  - composer install

before_script:
    - mkdir -p build/logs
    - mkdir -p build/cov

script:
  - phpunit --bootstrap helper/bootstrap.php test

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
