language: php
php:
  - 7.1.0
  - 7.1.12
  - 7.1.13
  - 7.1.27
  - 7.2.0
  - 7.2.28
  - 7.3.0
  - 7.3.15
  - 7.4.0
  - 7.4.3
  - nightly

branches:
  only:
  - master
  - develop

before_install:
  - travis_retry composer self-update
  - composer install

before_script:
    - mkdir -p build/logs
    - mkdir -p build/cov

script:
  - ./vendor/bin/phpunit --bootstrap helper/bootstrap.php test

after_script:
  - travis_retry php ./vendor/bin/php-coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
