language: php
php:
  - 7.1.3
  - 7.1.12
  - 7.1.13
  - 7.2

branches:
  only:
  - master
  - develop

before_install:
  - travis_retry composer self-update
  - composer install

before_script:
    - mkdir -p build/logs
    - mkdir -p build/cov

script:
  - phpunit --bootstrap helper/bootstrap.php test

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
